# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from omni.pro.protos.v1.airflow import register_model_pb2 as v1_dot_airflow_dot_register__model__pb2


class ModelsRegisterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ModelRegisterJob = channel.unary_unary(
            "/ModelsRegisterService/ModelRegisterJob",
            request_serializer=v1_dot_airflow_dot_register__model__pb2.ModelRegisterJobRequest.SerializeToString,
            response_deserializer=v1_dot_airflow_dot_register__model__pb2.ModelRegisterJobResponse.FromString,
        )


class ModelsRegisterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ModelRegisterJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ModelsRegisterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ModelRegisterJob": grpc.unary_unary_rpc_method_handler(
            servicer.ModelRegisterJob,
            request_deserializer=v1_dot_airflow_dot_register__model__pb2.ModelRegisterJobRequest.FromString,
            response_serializer=v1_dot_airflow_dot_register__model__pb2.ModelRegisterJobResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("ModelsRegisterService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ModelsRegisterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ModelRegisterJob(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ModelsRegisterService/ModelRegisterJob",
            v1_dot_airflow_dot_register__model__pb2.ModelRegisterJobRequest.SerializeToString,
            v1_dot_airflow_dot_register__model__pb2.ModelRegisterJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
