name: Deploy Python Library

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
     
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          pip3 install -r requirements.txt
      
      - name: Deploy Library on dist folder
        run: |
          python setup.py bdist_wheel
          ls -la dist/
      
      - name: Get next version
        id: generate_release_tag
        uses: phish108/autotag-action@1.1.53
        with:
          github-token: ${{ secrets.TOKEN_GITHUB}}
          with-v: "true"

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.generate_release_tag.outputs.new-tag }}"

  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.new-tag }}
          release_name: Release ${{ steps.generate_release_tag.outputs.new-tag }}
      
      - name: Upload assets to release created
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "dist/omni_pro-0.1.2-py3-none-any.whl"          
          asset_name: omni_pro-0.1.2-py3-none-any.whl.${{ steps.generate_tag.outputs.new-tag }}
          asset_content_type: application/zip
