name: Deploy Python Library

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
     
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          pip3 install -r requirements.txt
      
      - name: Deploy Library on dist folder
        run: |
          python setup.py bdist_wheel
          ls -la dist/
      
      - name: Get next version
        id: generate_release_tag
        uses: phish108/autotag-action@1.1.53
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          with-v: "true"

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.generate_release_tag.outputs.new-tag }}"
