name: Deploy Python Library

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      #- name: Login to AWS
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: <tu-region>
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          #npm install -g aws-cdk
          #pip3 install aws-cdk-lib
          pip3 install -r requirements.txt
          #wget -P workspace/saas-lambdas-layers/lambdas/users/login https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
      
      - name: Deploy Library on dist folder
        run: |
          python setup.py bdist_wheel
          ls -la dist/
      
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'

      - name: Print release tag 
        run: |
          echo "Tag Name"
          echo ${{steps.generate_release_tag.outputs.next_release_tag}}
          echo "Release Name"
          echo ${{steps.generate_release_tag.outputs.next_release_tag}}
