name: Deploy Python Library

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
     
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          pip3 install -r requirements.txt
      
      - name: Deploy Library on dist folder
        run: |
          python setup.py bdist_wheel
          ls -la dist/
      
      #- name: Generate release tag
      #  id: generate_tag
      #  uses: amitsingh-007/next-release-tag@v4.0.0
      #  with:
          #github_token: ${{ secrets.TOKEN_GITHUB }}
          #tag_prefix: 'v'
          #tag_template: 'yyyy.mm.dd.i'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
           GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
           #tag_name: ${{ steps.generate_tag.outputs.next_release_tag }}
           #release_name: Release ${{ steps.generate_tag.outputs.next_release_tag }}
           tag_name: v1.0.0
           release_name: "Release v1.0.0"
           draft: false
           prerelease: false

      - name: Upload assets to release created
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path: "dist/omni_pro-0.1.2-py3-none-any.whl"          
           asset_name: omni_pro-0.1.2-py3-none-any.whl.v1.0.0
           asset_content_type: application/zip
