name: Generate Files Python Library

on:
  push:
    branches:
      - master

jobs:
  deploy-patch:
    runs-on: ubuntu-latest
    #if: github.event_name == 'push' && contains(github.ref, 'tags/')
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          pip3 install -r requirements.txt

      - name: Get next version
        id: generate_release_tag
        uses: phish108/autotag-action@1.1.53
        with:
          github-token: ${{ secrets.TOKEN_GITHUB}}
          with-v: "true"
          bump: patch

      - name: Run Setup.py and Rename Files
        run: |
          python setup.py bdist_wheel -k
          ls -la dist/
          ls -la build/bdist.linux-x86_64/wheel/omni_pro-0.0.0.dist-info
          mv dist/omni_pro-0.0.0-py3-none-any.whl "dist/omni_pro-${{ steps.generate_release_tag.outputs.new-tag }}-py3-none-any.whl"
          mv build/bdist.linux-x86_64/wheel/omni_pro-0.0.0.dist-info "build/bdist.linux-x86_64/wheel/omni_pro-${{ steps.generate_release_tag.outputs.new-tag }}.dist-info"

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.generate_release_tag.outputs.new-tag }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.new-tag }}
          release_name: Release ${{ steps.generate_release_tag.outputs.new-tag }}

      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: dist/

#      - name: Publish package PYPI
#        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}


#  deploy-minor:
#    runs-on: ubuntu-latest
#    if: github.event_name == 'push' && !contains(github.ref, 'tags/')
#    steps:
#      - name: Checkout branch
#        uses: actions/checkout@v2
#
#      - name: Install Python dependencies
#        run: |
#          python -m pip install --upgrade pip
#          # install your Python dependencies here
#          pip3 install -r requirements.txt
#      - name: Deploy Library on dist folder
#        run: |
#          python setup.py bdist_wheel
#          ls -la dist/
#
#      - name: Get next version
#        id: generate_release_tag
#        uses: phish108/autotag-action@1.1.53
#        with:
#          github-token: ${{ secrets.TOKEN_GITHUB}}
#          with-v: "true"
#          bump: minor
#
#      - name: Check Output Parameters
#        run: |
#          echo "Got tag name ${{ steps.generate_release_tag.outputs.new-tag }}"
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
#        with:
#          tag_name: ${{ steps.generate_release_tag.outputs.new-tag }}
#          release_name: Release ${{ steps.generate_release_tag.outputs.new-tag }}
#
#      - name: Upload Release Assets
#        id: upload-release-assets
#        uses: dwenegar/upload-release-assets@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
#        with:
#          release_id: ${{ steps.create_release.outputs.id }}
#          assets_path: dist/
