name: Deploy Python Library

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
     
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          pip3 install -r requirements.txt
      
      - name: Deploy Library on dist folder
        run: |
          python setup.py bdist_wheel
          ls -la dist/
      
      - name: Get next version
        uses: technote-space/get-next-version-action@v1
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.NEXT_VERSION}`,
              sha: context.sha
            })

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.generate_release_tag.outputs.next }}"
